### PR TITLE
[WIP] Upgraded dependencies

### PR DESCRIPTION
**Pull request by fntlnz**
While working on a project that is using zend-*thing ~ 2.7 I wasn't able to use this anymore.
In this branch I'm working on checking if zendframework dependencies can be updated safely without breaking changes and if the whole project is compatibile with PHP 7.

Note: This is a work in progress. I needed the PR to run tests on travis.

### CODE REVIEW

**Comment by leogr** [comment]
Could you try to make it compatible with ZF ~ 2.5 too?
There are a lot of people are still using the 2.5.
You can use polyfills like [these](https://github.com/ripaclub/sphinxsearch/tree/0.7.1/compatibility)

**Comment by fntlnz** [comment]
@leogr Yes of course, Thanks for reminding me about those.

**Comment by leogr** [comment]
It seems to work with ZF 2.4 to 2.7, but not with zend-service-manager 3.0. due to BCs introduced within the new ServiceManager.

With zend-service-manager 3.0 I got the following error in a lot of tests:
`Argument 1 passed to Zend\ServiceManager\ServiceManager::__construct() must be of the type array, object given`
I think the only issue is about the two factory classes or may be just the tests are incompatible, not the library itself.

@fntlnz Could you try to investigate about this issue? Let me know.

**Comment by fntlnz** [comment]
@leogr since you're already working on this we may close this PR. Let me know if you need any help.

**Comment by leogr** [comment]
I fixed all compatibilities issue, now it works from 2.4 up to 3.0 (see the [last build](https://travis-ci.org/ripaclub/sphinxsearch/builds/118619425)).

@fntlnz if you rebase your PR then I merge the travis config, that can be very useful.

**Comment by fntlnz** [comment]
@leogr done!

**Comment by fntlnz** [comment]
All seems to be working pretty fine also with lower bound deps

https://travis-ci.org/ripaclub/sphinxsearch/builds/118620431

**Pull request merged**
